import { Phoneme, PhonemeGroup, PhonemeWord } from '@/types';

export const PHONEME_GROUPS: PhonemeGroup[] = [
  {
    id: 'plosives-nasals',
    label: 'Plosives & Nasals',
    phonemes: [
      { symbol: 'p', example: 'pin', group: 'plosive', englishEquivalence: 'p as in pin' },
      { symbol: 'b', example: 'bin', group: 'plosive', englishEquivalence: 'b as in bin' },
      { symbol: 't', example: 'tin', group: 'plosive', englishEquivalence: 't as in tin' },
      { symbol: 'd', example: 'din', group: 'plosive', englishEquivalence: 'd as in din' },
      { symbol: 'k', example: 'kin', group: 'plosive', englishEquivalence: 'k as in kin' },
      { symbol: 'g', example: 'gin', group: 'plosive', englishEquivalence: 'g as in gin' },
      { symbol: 'n', example: 'nine', group: 'nasal', englishEquivalence: 'n as in nine' },
      { symbol: 'm', example: 'mine', group: 'nasal', englishEquivalence: 'm as in mine' },
      { symbol: 'ŋ', example: 'sing', group: 'nasal', englishEquivalence: 'ng as in sing' },
    ],
  },
  {
    id: 'fricatives-approximants',
    label: 'Fricatives & Approximants',
    phonemes: [
      { symbol: 'f', example: 'fine', group: 'fricative', englishEquivalence: 'f as in fine' },
      { symbol: 'v', example: 'vine', group: 'fricative', englishEquivalence: 'v as in vine' },
      { symbol: 'θ', example: 'thin', group: 'fricative', englishEquivalence: 'th as in thin' },
      { symbol: 'ð', example: 'then', group: 'fricative', englishEquivalence: 'th as in then' },
      { symbol: 's', example: 'sin', group: 'fricative', englishEquivalence: 's as in sin' },
      { symbol: 'z', example: 'zip', group: 'fricative', englishEquivalence: 'z as in zip' },
      { symbol: 'ʃ', example: 'ship', group: 'fricative', englishEquivalence: 'sh as in ship' },
      { symbol: 'ʒ', example: 'vision', group: 'fricative', englishEquivalence: 'zh as in vision' },
      { symbol: 'h', example: 'hat', group: 'fricative', englishEquivalence: 'h as in hat' },
      { symbol: 'l', example: 'light', group: 'approximant', englishEquivalence: 'l as in light' },
      { symbol: 'ɹ', example: 'right', group: 'approximant', englishEquivalence: 'r as in right' },
      { symbol: 'w', example: 'win', group: 'approximant', englishEquivalence: 'w as in win' },
      { symbol: 'j', example: 'yes', group: 'approximant', englishEquivalence: 'y as in yes' },
      { symbol: 'tʃ', example: 'chin', group: 'approximant', englishEquivalence: 'ch as in chin' },
      { symbol: 'dʒ', example: 'jam', group: 'approximant', englishEquivalence: 'j as in jam' },
    ],
  },
  {
    id: 'monophthongs',
    label: 'Monophthongs',
    phonemes: [
      { symbol: 'iː', example: 'beet', group: 'monophthong', englishEquivalence: 'ee as in beet' },
      { symbol: 'ɪ', example: 'bit', group: 'monophthong', englishEquivalence: 'i as in bit' },
      { symbol: 'e', example: 'bet', group: 'monophthong', englishEquivalence: 'e as in bet' },
      { symbol: 'eː', example: 'bait', group: 'monophthong', englishEquivalence: 'ay as in bait' },
      { symbol: 'æ', example: 'bat', group: 'monophthong', englishEquivalence: 'a as in bat' },
      { symbol: 'ɐ', example: 'but', group: 'monophthong', englishEquivalence: 'u as in but' },
      { symbol: 'ɐː', example: 'bark', group: 'monophthong', englishEquivalence: 'ar as in bark' },
      { symbol: 'ɜː', example: 'bird', group: 'monophthong', englishEquivalence: 'ir as in bird' },
      { symbol: 'ʉː', example: 'boot', group: 'monophthong', englishEquivalence: 'oo as in boot' },
      { symbol: 'ɔ', example: 'log', group: 'monophthong', englishEquivalence: 'o as in log' },
      { symbol: 'oː', example: 'fork', group: 'monophthong', englishEquivalence: 'or as in fork' },
      { symbol: 'ʊ', example: 'book', group: 'monophthong', englishEquivalence: 'oo as in book' },
    ],
  },
  {
    id: 'diphthongs-schwa',
    label: 'Diphthongs & Schwa',
    phonemes: [
      { symbol: 'æɪ', example: 'bait', group: 'diphthong', englishEquivalence: 'ay as in bait' },
      { symbol: 'ɑe', example: 'bike', group: 'diphthong', englishEquivalence: 'ie as in bike' },
      { symbol: 'oɪ', example: 'boil', group: 'diphthong', englishEquivalence: 'oy as in boil' },
      { symbol: 'əʉ', example: 'boat', group: 'diphthong', englishEquivalence: 'oh as in boat' },
      { symbol: 'æɔ', example: 'cloud', group: 'diphthong', englishEquivalence: 'ow as in cloud' },
      { symbol: 'ɪə', example: 'beard', group: 'diphthong', englishEquivalence: 'ear as in beard' },
      { symbol: 'ə', example: 'about', group: 'diphthong', englishEquivalence: 'a as in about' },
    ],
  },
];

export const HCE_WORDS: PhonemeWord[] = [
  // 3 Phoneme Words
  { word: 'bed', phonemes: ['b', 'e', 'd'], transcription: 'b e d' },
  { word: 'bid', phonemes: ['b', 'ɪ', 'd'], transcription: 'b ɪ d' },
  { word: 'bad', phonemes: ['b', 'æ', 'd'], transcription: 'b æ d' },
  { word: 'bud', phonemes: ['b', 'ɐ', 'd'], transcription: 'b ɐ d' },
  { word: 'bird', phonemes: ['b', 'ɜː', 'd'], transcription: 'b ɜː d' },
  { word: 'bark', phonemes: ['b', 'ɐː', 'k'], transcription: 'b ɐː k' },
  { word: 'book', phonemes: ['b', 'ʊ', 'k'], transcription: 'b ʊ k' },
  { word: 'boot', phonemes: ['b', 'ʉː', 't'], transcription: 'b ʉː t' },
  { word: 'boat', phonemes: ['b', 'əʉ', 't'], transcription: 'b əʉ t' },
  { word: 'bike', phonemes: ['b', 'ɑe', 'k'], transcription: 'b ɑe k' },
  { word: 'bait', phonemes: ['b', 'æɪ', 't'], transcription: 'b æɪ t' },
  { word: 'boil', phonemes: ['b', 'oɪ', 'l'], transcription: 'b oɪ l' },
  { word: 'beard', phonemes: ['b', 'ɪə', 'd'], transcription: 'b ɪə d' },
  { word: 'thin', phonemes: ['θ', 'ɪ', 'n'], transcription: 'θ ɪ n' },
  { word: 'then', phonemes: ['ð', 'e', 'n'], transcription: 'ð e n' },
  { word: 'ship', phonemes: ['ʃ', 'ɪ', 'p'], transcription: 'ʃ ɪ p' },
  { word: 'chin', phonemes: ['tʃ', 'ɪ', 'n'], transcription: 'tʃ ɪ n' },
  { word: 'jam', phonemes: ['dʒ', 'æ', 'm'], transcription: 'dʒ æ m' },
  { word: 'yes', phonemes: ['j', 'e', 's'], transcription: 'j e s' },
  { word: 'win', phonemes: ['w', 'ɪ', 'n'], transcription: 'w ɪ n' },
  { word: 'ring', phonemes: ['ɹ', 'ɪ', 'ŋ'], transcription: 'ɹ ɪ ŋ' },
  { word: 'log', phonemes: ['l', 'ɔ', 'g'], transcription: 'l ɔ g' },
  { word: 'fan', phonemes: ['f', 'æ', 'n'], transcription: 'f æ n' },
  { word: 'van', phonemes: ['v', 'æ', 'n'], transcription: 'v æ n' },
  { word: 'sun', phonemes: ['s', 'ɐ', 'n'], transcription: 's ɐ n' },
  { word: 'zip', phonemes: ['z', 'ɪ', 'p'], transcription: 'z ɪ p' },
  { word: 'gum', phonemes: ['g', 'ɐ', 'm'], transcription: 'g ɐ m' },
  { word: 'hat', phonemes: ['h', 'æ', 't'], transcription: 'h æ t' },
  { word: 'fork', phonemes: ['f', 'oː', 'k'], transcription: 'f oː k' },
  { word: 'choice', phonemes: ['tʃ', 'oɪ', 's'], transcription: 'tʃ oɪ s' },
  
  // 4 Phoneme Words
  { word: 'stop', phonemes: ['s', 't', 'ɔ', 'p'], transcription: 's t ɔ p' },
  { word: 'frog', phonemes: ['f', 'ɹ', 'ɔ', 'g'], transcription: 'f ɹ ɔ g' },
  { word: 'clap', phonemes: ['k', 'l', 'æ', 'p'], transcription: 'k l æ p' },
  { word: 'slip', phonemes: ['s', 'l', 'ɪ', 'p'], transcription: 's l ɪ p' },
  { word: 'drum', phonemes: ['d', 'ɹ', 'ɐ', 'm'], transcription: 'd ɹ ɐ m' },
  { word: 'grin', phonemes: ['g', 'ɹ', 'ɪ', 'n'], transcription: 'g ɹ ɪ n' },
  { word: 'train', phonemes: ['t', 'ɹ', 'æɪ', 'n'], transcription: 't ɹ æɪ n' },
  { word: 'cloud', phonemes: ['k', 'l', 'æɔ', 'd'], transcription: 'k l æɔ d' },
  { word: 'snake', phonemes: ['s', 'n', 'æɪ', 'k'], transcription: 's n æɪ k' },
  { word: 'smile', phonemes: ['s', 'm', 'ɑe', 'l'], transcription: 's m ɑe l' },
  { word: 'milk', phonemes: ['m', 'ɪ', 'l', 'k'], transcription: 'm ɪ l k' },
  { word: 'hand', phonemes: ['h', 'æ', 'n', 'd'], transcription: 'h æ n d' },
  { word: 'tent', phonemes: ['t', 'e', 'n', 't'], transcription: 't e n t' },
  { word: 'jump', phonemes: ['dʒ', 'ɐ', 'm', 'p'], transcription: 'dʒ ɐ m p' },
  { word: 'lamp', phonemes: ['l', 'æ', 'm', 'p'], transcription: 'l æ m p' },
  { word: 'bank', phonemes: ['b', 'æ', 'ŋ', 'k'], transcription: 'b æ ŋ k' },
  { word: 'frame', phonemes: ['f', 'ɹ', 'æɪ', 'm'], transcription: 'f ɹ æɪ m' },
  { word: 'cold', phonemes: ['k', 'əʉ', 'l', 'd'], transcription: 'k əʉ l d' },
  { word: 'wind', phonemes: ['w', 'ɪ', 'n', 'd'], transcription: 'w ɪ n d' },
  { word: 'soft', phonemes: ['s', 'ɔ', 'f', 't'], transcription: 's ɔ f t' },
  { word: 'gift', phonemes: ['g', 'ɪ', 'f', 't'], transcription: 'g ɪ f t' },
  { word: 'desk', phonemes: ['d', 'e', 's', 'k'], transcription: 'd e s k' },
  { word: 'left', phonemes: ['l', 'e', 'f', 't'], transcription: 'l e f t' },
  { word: 'pond', phonemes: ['p', 'ɔ', 'n', 'd'], transcription: 'p ɔ n d' },
  { word: 'golf', phonemes: ['g', 'ɔ', 'l', 'f'], transcription: 'g ɔ l f' },
  { word: 'silk', phonemes: ['s', 'ɪ', 'l', 'k'], transcription: 's ɪ l k' },
  { word: 'great', phonemes: ['g', 'ɹ', 'æɪ', 't'], transcription: 'g ɹ æɪ t' },
  { word: 'crab', phonemes: ['k', 'ɹ', 'æ', 'b'], transcription: 'k ɹ æ b' },
  { word: 'plug', phonemes: ['p', 'l', 'ɐ', 'g'], transcription: 'p l ɐ g' },
  { word: 'quiz', phonemes: ['k', 'w', 'ɪ', 'z'], transcription: 'k w ɪ z' },
  
  // 5 Phoneme Words
  { word: 'stamp', phonemes: ['s', 't', 'æ', 'm', 'p'], transcription: 's t æ m p' },
  { word: 'plant', phonemes: ['p', 'l', 'æ', 'n', 't'], transcription: 'p l æ n t' },
  { word: 'blank', phonemes: ['b', 'l', 'æ', 'ŋ', 'k'], transcription: 'b l æ ŋ k' },
  { word: 'grand', phonemes: ['g', 'ɹ', 'æ', 'n', 'd'], transcription: 'g ɹ æ n d' },
  { word: 'clamp', phonemes: ['k', 'l', 'æ', 'm', 'p'], transcription: 'k l æ m p' },
  { word: 'twist', phonemes: ['t', 'w', 'ɪ', 's', 't'], transcription: 't w ɪ s t' },
  { word: 'trust', phonemes: ['t', 'ɹ', 'ɐ', 's', 't'], transcription: 't ɹ ɐ s t' },
  { word: 'drink', phonemes: ['d', 'ɹ', 'ɪ', 'ŋ', 'k'], transcription: 'd ɹ ɪ ŋ k' },
  { word: 'brisk', phonemes: ['b', 'ɹ', 'ɪ', 's', 'k'], transcription: 'b ɹ ɪ s k' },
  { word: 'shrimp', phonemes: ['ʃ', 'ɹ', 'ɪ', 'm', 'p'], transcription: 'ʃ ɹ ɪ m p' },
  { word: 'scrap', phonemes: ['s', 'k', 'ɹ', 'æ', 'p'], transcription: 's k ɹ æ p' },
  { word: 'scribe', phonemes: ['s', 'k', 'ɹ', 'ɑe', 'b'], transcription: 's k ɹ ɑe b' },
  { word: 'scream', phonemes: ['s', 'k', 'ɹ', 'iː', 'm'], transcription: 's k ɹ iː m' },
  { word: 'splash', phonemes: ['s', 'p', 'l', 'æ', 'ʃ'], transcription: 's p l æ ʃ' },
  { word: 'spring', phonemes: ['s', 'p', 'ɹ', 'ɪ', 'ŋ'], transcription: 's p ɹ ɪ ŋ' },
  { word: 'strap', phonemes: ['s', 't', 'ɹ', 'æ', 'p'], transcription: 's t ɹ æ p' },
  { word: 'street', phonemes: ['s', 't', 'ɹ', 'iː', 't'], transcription: 's t ɹ iː t' },
  { word: 'scrub', phonemes: ['s', 'k', 'ɹ', 'ɐ', 'b'], transcription: 's k ɹ ɐ b' },
  { word: 'flask', phonemes: ['f', 'l', 'ɐː', 's', 'k'], transcription: 'f l ɐː s k' },
  { word: 'clasp', phonemes: ['k', 'l', 'ɐː', 's', 'p'], transcription: 'k l ɐː s p' },
  { word: 'cleft', phonemes: ['k', 'l', 'e', 'f', 't'], transcription: 'k l e f t' },
  { word: 'glint', phonemes: ['g', 'l', 'ɪ', 'n', 't'], transcription: 'g l ɪ n t' },
  { word: 'blend', phonemes: ['b', 'l', 'e', 'n', 'd'], transcription: 'b l e n d' },
  { word: 'strain', phonemes: ['s', 't', 'ɹ', 'æɪ', 'n'], transcription: 's t ɹ æɪ n' },
  { word: 'thrust', phonemes: ['θ', 'ɹ', 'ɐ', 's', 't'], transcription: 'θ ɹ ɐ s t' },
  { word: 'sprawl', phonemes: ['s', 'p', 'ɹ', 'oː', 'l'], transcription: 's p ɹ oː l' },
  { word: 'scrawl', phonemes: ['s', 'k', 'ɹ', 'oː', 'l'], transcription: 's k ɹ oː l' },
  { word: 'sprig', phonemes: ['s', 'p', 'ɹ', 'ɪ', 'g'], transcription: 's p ɹ ɪ g' },
  { word: 'sprout', phonemes: ['s', 'p', 'ɹ', 'æɔ', 't'], transcription: 's p ɹ æɔ t' },
  { word: 'smoked', phonemes: ['s', 'm', 'əʉ', 'k', 't'], transcription: 's m əʉ k t' },
];

export const getPhonemeBySymbol = (symbol: string): Phoneme | undefined => {
  for (const group of PHONEME_GROUPS) {
    const found = group.phonemes.find(p => p.symbol === symbol);
    if (found) return found;
  }
  return undefined;
};

export const getPhonemeColor = (group: string): string => {
  const colors = {
    plosive: 'bg-red-500 hover:bg-red-600',
    nasal: 'bg-purple-500 hover:bg-purple-600',
    fricative: 'bg-yellow-500 hover:bg-yellow-600',
    approximant: 'bg-green-500 hover:bg-green-600',
    monophthong: 'bg-blue-500 hover:bg-blue-600',
    diphthong: 'bg-pink-500 hover:bg-pink-600',
  };
  return colors[group as keyof typeof colors] || 'bg-gray-500 hover:bg-gray-600';
};